
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author matat
 */
public class foerLoteria extends javax.swing.JFrame {
    
    Loteria lot = new Loteria();

    /**
     * Creates new form foerLoteria
     */
    public foerLoteria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelLoteria = new javax.swing.JLabel();
        LabelAposta = new javax.swing.JLabel();
        LabelSorteio = new javax.swing.JLabel();
        LabelN1 = new javax.swing.JLabel();
        TextN1 = new javax.swing.JTextField();
        LabelN2 = new javax.swing.JLabel();
        TextN2 = new javax.swing.JTextField();
        LabelN3 = new javax.swing.JLabel();
        TextN3 = new javax.swing.JTextField();
        LabelN4 = new javax.swing.JLabel();
        TextN4 = new javax.swing.JTextField();
        LabelN5 = new javax.swing.JLabel();
        TextN5 = new javax.swing.JTextField();
        LabelNS4 = new javax.swing.JLabel();
        TextNS4 = new javax.swing.JTextField();
        LabelNS5 = new javax.swing.JLabel();
        TextNS5 = new javax.swing.JTextField();
        LabelNS1 = new javax.swing.JLabel();
        TextNS1 = new javax.swing.JTextField();
        LabelNS2 = new javax.swing.JLabel();
        TextNS2 = new javax.swing.JTextField();
        LabelNS3 = new javax.swing.JLabel();
        TextNS3 = new javax.swing.JTextField();
        ButSorteio = new javax.swing.JButton();
        ButCadastroAposta = new javax.swing.JButton();
        LabelNAcertos = new javax.swing.JLabel();
        TextNAcerto = new javax.swing.JTextField();
        LabelPremio = new javax.swing.JLabel();
        TextPremiação = new javax.swing.JTextField();
        ButExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelLoteria.setText("Loretia");

        LabelAposta.setText("Aposta");

        LabelSorteio.setText("Sorteados");

        LabelN1.setText("N1");

        TextN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextN1ActionPerformed(evt);
            }
        });

        LabelN2.setText("N2");

        TextN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextN2ActionPerformed(evt);
            }
        });

        LabelN3.setText("N3");

        TextN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextN3ActionPerformed(evt);
            }
        });

        LabelN4.setText("N4");

        TextN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextN4ActionPerformed(evt);
            }
        });

        LabelN5.setText("N5");

        TextN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextN5ActionPerformed(evt);
            }
        });

        LabelNS4.setText("N4");

        TextNS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNS4ActionPerformed(evt);
            }
        });

        LabelNS5.setText("N5");

        TextNS5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNS5ActionPerformed(evt);
            }
        });

        LabelNS1.setText("N1");

        TextNS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNS1ActionPerformed(evt);
            }
        });

        LabelNS2.setText("N2");

        TextNS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNS2ActionPerformed(evt);
            }
        });

        LabelNS3.setText("N3");

        TextNS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNS3ActionPerformed(evt);
            }
        });

        ButSorteio.setText("Sortear");
        ButSorteio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSorteioActionPerformed(evt);
            }
        });

        ButCadastroAposta.setText("Cadastrar Aposta");
        ButCadastroAposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCadastroApostaActionPerformed(evt);
            }
        });

        LabelNAcertos.setText("NºAcertados");

        LabelPremio.setText("Premiação");

        TextPremiação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPremiaçãoActionPerformed(evt);
            }
        });

        ButExit.setForeground(new java.awt.Color(255, 0, 0));
        ButExit.setText("Exit");
        ButExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(LabelAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelSorteio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButExit)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelN2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(TextN2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelN1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(TextN1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelN3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(TextN3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelN4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(TextN4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelN5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(TextN5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ButSorteio)
                    .addComponent(ButCadastroAposta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelLoteria, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelNS2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(TextNS2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelNS1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(TextNS1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelNS3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(TextNS3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelNS4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(TextNS4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelNS5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(TextNS5))
                            .addComponent(TextPremiação)
                            .addComponent(TextNAcerto))))
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelLoteria)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAposta)
                    .addComponent(LabelSorteio))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelN1)
                            .addComponent(TextN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelN2)
                            .addComponent(TextN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelN3)
                            .addComponent(TextN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelN4)
                            .addComponent(TextN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelN5)
                            .addComponent(TextN5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNS1)
                            .addComponent(TextNS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNS2)
                            .addComponent(TextNS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNS3)
                            .addComponent(TextNS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNS4)
                            .addComponent(TextNS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNS5)
                            .addComponent(TextNS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButCadastroAposta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNAcerto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNAcertos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButSorteio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPremio)
                    .addComponent(TextPremiação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(ButExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextN1ActionPerformed

    private void TextN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextN2ActionPerformed

    private void TextN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextN3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextN3ActionPerformed

    private void TextN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextN4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextN4ActionPerformed

    private void TextN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextN5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextN5ActionPerformed

    private void TextNS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNS4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNS4ActionPerformed

    private void TextNS5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNS5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNS5ActionPerformed

    private void TextNS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNS1ActionPerformed

    private void TextNS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNS2ActionPerformed

    private void TextNS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNS3ActionPerformed

    // sorteia os numeros, mostra o acertos, mostra o valor ganhado
    private void ButSorteioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSorteioActionPerformed
        // TODO add your handling code here:
        lot.Sortear();
        this.TextNS1.setText(""+ lot.ns1);
        this.TextNS2.setText(""+ lot.ns2);
        this.TextNS3.setText(""+ lot.ns3);
        this.TextNS4.setText(""+ lot.ns4);
        this.TextNS5.setText(""+ lot.ns5);
        this.TextNAcerto.setText(""+ lot.CalcAcertos());
        this.TextPremiação.setText(""+ lot.VerificaPremio(lot.CalcAcertos()));
    }//GEN-LAST:event_ButSorteioActionPerformed

    //pega o valor dos textN
    private void ButCadastroApostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCadastroApostaActionPerformed
        // TODO add your handling code here:
        lot.n1 = Integer.parseInt(this.TextN1.getText());
        lot.n2 = Integer.parseInt(this.TextN2.getText());
        lot.n3 = Integer.parseInt(this.TextN3.getText());
        lot.n4 = Integer.parseInt(this.TextN4.getText());
        lot.n5 = Integer.parseInt(this.TextN5.getText());
        JOptionPane.showMessageDialog(null, "aposta cadastrado com sucesso!!!");
        
    }//GEN-LAST:event_ButCadastroApostaActionPerformed

    private void TextPremiaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPremiaçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPremiaçãoActionPerformed

    // botao de sair
    private void ButExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foerLoteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foerLoteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foerLoteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foerLoteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foerLoteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButCadastroAposta;
    private javax.swing.JButton ButExit;
    private javax.swing.JButton ButSorteio;
    private javax.swing.JLabel LabelAposta;
    private javax.swing.JLabel LabelLoteria;
    private javax.swing.JLabel LabelN1;
    private javax.swing.JLabel LabelN2;
    private javax.swing.JLabel LabelN3;
    private javax.swing.JLabel LabelN4;
    private javax.swing.JLabel LabelN5;
    private javax.swing.JLabel LabelNAcertos;
    private javax.swing.JLabel LabelNS1;
    private javax.swing.JLabel LabelNS2;
    private javax.swing.JLabel LabelNS3;
    private javax.swing.JLabel LabelNS4;
    private javax.swing.JLabel LabelNS5;
    private javax.swing.JLabel LabelPremio;
    private javax.swing.JLabel LabelSorteio;
    private javax.swing.JTextField TextN1;
    private javax.swing.JTextField TextN2;
    private javax.swing.JTextField TextN3;
    private javax.swing.JTextField TextN4;
    private javax.swing.JTextField TextN5;
    private javax.swing.JTextField TextNAcerto;
    private javax.swing.JTextField TextNS1;
    private javax.swing.JTextField TextNS2;
    private javax.swing.JTextField TextNS3;
    private javax.swing.JTextField TextNS4;
    private javax.swing.JTextField TextNS5;
    private javax.swing.JTextField TextPremiação;
    // End of variables declaration//GEN-END:variables
}
