
public class FormEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form FormEmpresa
     */
    public FormEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelEmpresa = new javax.swing.JLabel();
        ButMensalista = new javax.swing.JButton();
        ButHorista = new javax.swing.JButton();
        ButAutonomo = new javax.swing.JButton();
        ButExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelEmpresa.setText("Empresa");

        ButMensalista.setText("Mensalista");
        ButMensalista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButMensalistaActionPerformed(evt);
            }
        });

        ButHorista.setText("Horista");
        ButHorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButHoristaActionPerformed(evt);
            }
        });

        ButAutonomo.setText("Autonomo");
        ButAutonomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAutonomoActionPerformed(evt);
            }
        });

        ButExit.setBackground(new java.awt.Color(204, 0, 51));
        ButExit.setForeground(new java.awt.Color(255, 255, 0));
        ButExit.setText("Exit");
        ButExit.setToolTipText("");
        ButExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(LabelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ButMensalista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButHorista)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButAutonomo)
                    .addComponent(ButExit))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LabelEmpresa)
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButMensalista)
                    .addComponent(ButHorista)
                    .addComponent(ButAutonomo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(ButExit)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ir para o form de mensalista
    private void ButMensalistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButMensalistaActionPerformed
        // TODO add your handling code here:
        new FormMensalista().setVisible(true);
        dispose();
    }//GEN-LAST:event_ButMensalistaActionPerformed

    // ir para o form de horista
    private void ButHoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButHoristaActionPerformed
        // TODO add your handling code here:
        new FormHorista().setVisible(true);
        dispose();
    }//GEN-LAST:event_ButHoristaActionPerformed

    //botao para sair do programa
    private void ButExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButExitActionPerformed

    // ir para o form Autonomo
    private void ButAutonomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAutonomoActionPerformed
        // TODO add your handling code here:
        new FormAutonomo().setVisible(true);
        dispose();
    }//GEN-LAST:event_ButAutonomoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAutonomo;
    private javax.swing.JButton ButExit;
    private javax.swing.JButton ButHorista;
    private javax.swing.JButton ButMensalista;
    private javax.swing.JLabel LabelEmpresa;
    // End of variables declaration//GEN-END:variables
}
