
import javax.swing.JOptionPane;


public class FormMensalista extends javax.swing.JFrame {
    Mensalista men = new Mensalista();
    /**
     * Creates new form FormMensalista
     */
    public FormMensalista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelMensalista = new javax.swing.JLabel();
        LabelNome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextNome = new javax.swing.JTextPane();
        LabelRegistro = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextResg = new javax.swing.JTextPane();
        LabelSalBruto = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextSalBruto = new javax.swing.JTextPane();
        LabelDesconto = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextDesconto = new javax.swing.JTextPane();
        ButCadastrar = new javax.swing.JButton();
        ButExibir = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TextSalario = new javax.swing.JTextPane();
        ButCalcular = new javax.swing.JButton();
        LabelSalario = new javax.swing.JLabel();
        ButHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelMensalista.setText("Mensalista");

        LabelNome.setText("Nome");

        jScrollPane1.setViewportView(TextNome);

        LabelRegistro.setText("Registro");

        jScrollPane2.setViewportView(TextResg);

        LabelSalBruto.setText("Salario Bruto");

        jScrollPane3.setViewportView(TextSalBruto);

        LabelDesconto.setText("Desconto");

        jScrollPane4.setViewportView(TextDesconto);

        ButCadastrar.setText("Cadastrar");
        ButCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCadastrarActionPerformed(evt);
            }
        });

        ButExibir.setText("Exibir");
        ButExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExibirActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(TextSalario);

        ButCalcular.setText("Calcular");
        ButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCalcularActionPerformed(evt);
            }
        });

        LabelSalario.setText("Salario");

        ButHome.setBackground(new java.awt.Color(204, 51, 0));
        ButHome.setForeground(new java.awt.Color(255, 255, 0));
        ButHome.setText("Home");
        ButHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(172, 172, 172)
                            .addComponent(LabelMensalista, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelSalBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(LabelSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(ButCadastrar)
                .addGap(128, 128, 128)
                .addComponent(ButExibir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButCalcular)
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ButHome)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LabelMensalista)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNome)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelRegistro)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSalBruto)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelDesconto)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButCadastrar)
                    .addComponent(ButExibir)
                    .addComponent(ButCalcular))
                .addGap(4, 4, 4)
                .addComponent(ButHome)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //botao de cadastrar ainformacao nos atributos
    private void ButCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCadastrarActionPerformed
        // TODO add your handling code here:
        //para pegar os atributos dos campos de texto
        men.nome = this.TextNome.getText();
        men.reg = Integer.parseInt(this.TextResg.getText());
        men.salBruto = Double.parseDouble(this.TextSalBruto.getText());
        men.desconto = Double.parseDouble(this.TextDesconto.getText());
        // menssagem de confirmacao de cadastro
        JOptionPane.showMessageDialog(null, "valores cadastrado com sucesso!!!");
        
        // limoa os campos de texto
        this.TextNome.setText("");
        this.TextResg.setText("");
        this.TextSalBruto.setText("");
        this.TextDesconto.setText("");
        
    }//GEN-LAST:event_ButCadastrarActionPerformed

    // voltar prar o form da empresa
    private void ButHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButHomeActionPerformed
        // TODO add your handling code here:
        new FormEmpresa().setVisible(true);
        dispose();
    }//GEN-LAST:event_ButHomeActionPerformed

    // para exibir os valores cadastrados
    private void ButExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExibirActionPerformed
        // TODO add your handling code here:
        // exibir os valores cadastrados
        this.TextNome.setText(men.nome);
        this.TextResg.setText(men.reg +"");
        this.TextSalBruto.setText(""+ men.salBruto);
        this.TextDesconto.setText(""+ men.desconto);
        
    }//GEN-LAST:event_ButExibirActionPerformed

    // botao de calcular o salario
    private void ButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCalcularActionPerformed
        // TODO add your handling code here:
        // para exibir o salario
        this.TextSalario.setText(""+ men.CalcSal());
    }//GEN-LAST:event_ButCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButCadastrar;
    private javax.swing.JButton ButCalcular;
    private javax.swing.JButton ButExibir;
    private javax.swing.JButton ButHome;
    private javax.swing.JLabel LabelDesconto;
    private javax.swing.JLabel LabelMensalista;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelRegistro;
    private javax.swing.JLabel LabelSalBruto;
    private javax.swing.JLabel LabelSalario;
    private javax.swing.JTextPane TextDesconto;
    private javax.swing.JTextPane TextNome;
    private javax.swing.JTextPane TextResg;
    private javax.swing.JTextPane TextSalBruto;
    private javax.swing.JTextPane TextSalario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
